
haopiao@haogongsi:~/workspace (master) $ heroku logs 
2015-02-14T12:50:28.122226+00:00 heroku[api]: Enable Logplex by amateurlee@sina.com
2015-02-14T12:50:28.122226+00:00 heroku[api]: Release v2 created by amateurlee@sina.com
2015-02-14T12:52:00.257645+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/?_c9_id=livepreview0&_c9_host=https://ide.c9.io" host=haogongsi.herokuapp.com request_id=ec344aad-1dce-4c6e-8426-24a91cfd62eb fwd="124.205.254.4" dyno= connect= service= status=502 bytes=
2015-02-14T13:05:03.621248+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=haogongsi.herokuapp.com request_id=13b30c80-ed79-4be9-8c1b-043b94bd512f fwd="124.205.254.4" dyno= connect= service= status=502 bytes=
2015-02-14T13:05:04.254412+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=haogongsi.herokuapp.com request_id=b98a12d0-5eb9-49b8-a351-314be062793d fwd="124.205.254.4" dyno= connect= service= status=502 bytes=
2015-02-14T13:05:07.875375+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=haogongsi.herokuapp.com request_id=6186ef55-a25a-4048-b941-86b62b7d75d0 fwd="124.205.254.4" dyno= connect= service= status=502 bytes=
2015-02-14T13:45:15.564866+00:00 heroku[api]: Set DATABASE_URL config vars by amateurlee@sina.com
2015-02-14T13:45:15.564866+00:00 heroku[api]: Release v3 created by amateurlee@sina.com
2015-02-14T13:45:15.630650+00:00 heroku[api]: Attach HEROKU_POSTGRESQL_CHARCOAL resource by amateurlee@sina.com
2015-02-14T13:45:15.630650+00:00 heroku[api]: Release v4 created by amateurlee@sina.com
2015-02-14T13:45:16.201178+00:00 heroku[api]: Deploy 51fdfb0 by amateurlee@sina.com
2015-02-14T13:45:16.201223+00:00 heroku[api]: Release v5 created by amateurlee@sina.com
2015-02-14T13:48:20.140198+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=haogongsi.herokuapp.com request_id=934d79ee-1d4b-47dc-8524-859dd3fbb2d2 fwd="125.39.68.35" dyno= connect= service= status=503 bytes=
2015-02-14T13:50:19.634265+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=haogongsi.herokuapp.com request_id=a85f118c-cd9b-420e-9342-91d4a2043db8 fwd="125.39.68.35" dyno= connect= service= status=503 bytes=
2015-02-14T14:30:08.356114+00:00 heroku[api]: Deploy 6d03bd8 by amateurlee@sina.com
2015-02-14T14:30:08.356114+00:00 heroku[api]: Release v6 created by amateurlee@sina.com
2015-02-14T14:33:36.859508+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=haogongsi.herokuapp.com request_id=48f9c709-1d9f-4cbc-9a22-1076cbcbcf18 fwd="124.205.254.4" dyno= connect= service= status=503 bytes=
2015-02-14T14:33:48.731301+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=haogongsi.herokuapp.com request_id=507584f5-65e7-4a01-90d0-f0705cbc3f75 fwd="124.205.254.4" dyno= connect= service= status=503 bytes=
2015-02-14T14:35:25.188615+00:00 heroku[api]: Scale to web=1 by amateurlee@sina.com
2015-02-14T14:35:29.694274+00:00 heroku[web.1]: Starting process with command `gunicorn haogongsi.wsgi --log-file -`
2015-02-14T14:35:31.342740+00:00 app[web.1]: 2015-02-14 14:35:31 [3] [INFO] Listening at: http://0.0.0.0:8321 (3)
2015-02-14T14:35:31.369008+00:00 app[web.1]: 2015-02-14 14:35:31 [9] [INFO] Booting worker with pid: 9
2015-02-14T14:35:31.342827+00:00 app[web.1]: 2015-02-14 14:35:31 [3] [INFO] Using worker: sync
2015-02-14T14:35:31.402248+00:00 app[web.1]: 2015-02-14 14:35:31 [10] [INFO] Booting worker with pid: 10
2015-02-14T14:35:31.342038+00:00 app[web.1]: 2015-02-14 14:35:31 [3] [INFO] Starting gunicorn 19.0.0
2015-02-14T14:35:31.431075+00:00 heroku[web.1]: State changed from starting to up
2015-02-14T14:36:13.163450+00:00 heroku[router]: at=info method=GET path="/" host=haogongsi.herokuapp.com request_id=b79adfa5-c418-4b7d-b4f1-b742b79173db fwd="124.205.254.4" dyno=web.1 connect=1ms service=458ms status=500 bytes=244
2015-02-14T14:36:13.157058+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T14:36:13.157060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-02-14T14:36:13.157063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-02-14T14:36:13.157070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
2015-02-14T14:36:13.157051+00:00 app[web.1]: 2015-02-14 14:36:13 [9] [ERROR] Error handling request
2015-02-14T14:36:13.157061+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-14T14:36:13.157066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-02-14T14:36:13.157065+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-14T14:36:13.157068+00:00 app[web.1]:     self.load_middleware()
2015-02-14T14:36:13.157071+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2015-02-14T14:36:13.157074+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
2015-02-14T14:36:13.157099+00:00 app[web.1]:     error_prefix, module_path, class_name))
2015-02-14T14:36:13.157102+00:00 app[web.1]: ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
2015-02-14T14:46:55.336300+00:00 heroku[router]: at=info method=GET path="/" host=haogongsi.herokuapp.com request_id=87f23dfc-84d0-4539-a269-bdd555a45b72 fwd="124.205.254.4" dyno=web.1 connect=1ms service=91ms status=500 bytes=244
2015-02-14T14:46:55.340587+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-02-14T14:46:55.340595+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2015-02-14T14:46:55.340588+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-14T14:46:55.340594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
2015-02-14T14:46:55.340581+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T14:46:55.340577+00:00 app[web.1]: 2015-02-14 14:46:55 [10] [ERROR] Error handling request
2015-02-14T14:46:55.340583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-02-14T14:46:55.340585+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-14T14:46:55.340592+00:00 app[web.1]:     self.load_middleware()
2015-02-14T14:46:55.340601+00:00 app[web.1]: ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
2015-02-14T14:46:55.340590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-02-14T14:46:55.340597+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
2015-02-14T14:46:55.340598+00:00 app[web.1]:     error_prefix, module_path, class_name))
2015-02-14T14:47:52.473015+00:00 heroku[router]: at=info method=GET path="/?_c9_id=livepreview0&_c9_host=https://ide.c9.io" host=haogongsi.herokuapp.com request_id=beb55c25-2c70-4e3d-8e6d-c8d829a70471 fwd="124.205.254.4" dyno=web.1 connect=14ms service=2ms status=500 bytes=244
2015-02-14T14:47:52.477357+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T14:47:52.477359+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-02-14T14:47:52.477366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-02-14T14:47:52.477372+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
2015-02-14T14:47:52.477370+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2015-02-14T14:47:52.477364+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-14T14:47:52.477362+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-02-14T14:47:52.477361+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-14T14:47:52.477369+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
2015-02-14T14:47:52.477351+00:00 app[web.1]: 2015-02-14 14:47:52 [10] [ERROR] Error handling request
2015-02-14T14:47:52.477367+00:00 app[web.1]:     self.load_middleware()
2015-02-14T14:47:52.477373+00:00 app[web.1]:     error_prefix, module_path, class_name))
2015-02-14T14:47:52.477375+00:00 app[web.1]: ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
2015-02-14T14:51:40.071523+00:00 heroku[router]: at=info method=GET path="/" host=haogongsi.herokuapp.com request_id=51bb1e8a-f407-4058-8aa5-87d5e44a1213 fwd="124.205.254.4" dyno=web.1 connect=15ms service=13ms status=500 bytes=244
2015-02-14T14:51:40.064923+00:00 app[web.1]: 2015-02-14 14:51:40 [10] [ERROR] Error handling request
2015-02-14T14:51:40.064937+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-02-14T14:51:40.064929+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T14:51:40.064941+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-02-14T14:51:40.064946+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
2015-02-14T14:51:40.064939+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-14T14:51:40.064944+00:00 app[web.1]:     self.load_middleware()
2015-02-14T14:51:40.064948+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2015-02-14T14:51:40.064950+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
2015-02-14T14:51:40.064953+00:00 app[web.1]:     error_prefix, module_path, class_name))
2015-02-14T14:51:40.064955+00:00 app[web.1]: ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
2015-02-14T14:51:40.064932+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-02-14T14:51:40.064934+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-14T14:56:15.635163+00:00 heroku[router]: at=info method=GET path="/" host=haogongsi.herokuapp.com request_id=93f08166-5d3c-461b-858c-52b5f4220fac fwd="124.205.254.4" dyno=web.1 connect=1ms service=4ms status=500 bytes=244
2015-02-14T14:56:15.637362+00:00 app[web.1]: 2015-02-14 14:56:15 [10] [ERROR] Error handling request
2015-02-14T14:56:15.637369+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T14:56:15.637372+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-02-14T14:56:15.637409+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-14T14:56:15.637407+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-02-14T14:56:15.637405+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-14T14:56:15.637412+00:00 app[web.1]:     self.load_middleware()
2015-02-14T14:56:15.637410+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-02-14T14:56:15.637414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
2015-02-14T14:56:15.637416+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2015-02-14T14:56:15.637417+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
2015-02-14T14:56:15.637419+00:00 app[web.1]:     error_prefix, module_path, class_name))
2015-02-14T14:56:15.637421+00:00 app[web.1]: ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class